{
  imports = [
    ./boot.nix
    ./dns.nix
    ./flatpak.nix
    ./fonts.nix
    ./graphics.nix
    ./greetd.nix
    ./hyprland.nix
    ./keyboard.nix
    ./locale.nix
    ./lsp.nix
    ./networking.nix
    ./nix.nix
    ./nixpkgs.nix
    ./security.nix
    ./ssh.nix
    ./state-version.nix
    ./tailscale.nix
    ./users.nix
  ];
}
